[tool.poetry]
name = "microkit"
version = "0.1.0"
description = ""
authors = ["ronghuideng <1343901798@qq.com>"]
packages = [
    {include = "microkit"}
]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
